### ISSUE TITLE
readiness_test_synchronous does not go through all checks in yaml file, just the last one

### ISSUE THREAD

**Issue by nsevilla** [patricialarsen/descqa#3]
when running this test, all quantities are checked against the requirements of the last one in the yaml file. I think it is an indentation issue in the block after 

for i, checks in enumerate(self.quantities_to_check):
...

I think the block following that should be indented or within the checks loop somehow, otherwise it always picks up the last checks value.

**Comment by patricialarsen** [comment]
Will fix this, extracting that block was a read-in optimization so we wouldn't be looping over the read-in for each quantity, but I messed up the quantity metadata that was carried along in doing so

**Comment by patricialarsen** [comment]
fixed in latest commit
